service: pedirPizzas

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  hacerPedido:
    handler: handler.hacerPedido
    events:
      - http:
          method: post
          path: pedido
